### PR TITLE
Update embedded-svc

### PR DESCRIPTION
**Pull request by DaneSlattery**
Update the dependencies and bump the version

### CODE REVIEW

**Comment by DaneSlattery** [comment]
In the edge-net stack and across the board in my projects, this `embedded-svc` is the only one on the "old" release of `embedded-svc`

**Comment by ivmarkov** [comment]
Does it build properly with the `embedded-svc` feature enabled?

**Comment by ivmarkov** [comment]
You might also want to update `edge-ws` to 0.3

**Comment by DaneSlattery** [comment]
I've tested it with `embedded-svc` and `ws` features enabled (it builds)

**Comment by ivmarkov** [comment]
OK - merging. But raising `edge-ws` to 0.3 is still a good idea.

**Comment by DaneSlattery** [comment]
I did raise edge-ws 👍

**Comment by ivmarkov** [comment]
Ah yes - thanks!

**Pull request merged**
